Politify/Controllers/DiscussionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Politify.Code;
using Politify.Models;

namespace Politify.Controllers
{
    public class DiscussionController : Controller
    {
        private PolitifyDbContext db = new PolitifyDbContext();

        // GET: Discussion
        public ActionResult Index()
        {
            return View();        
        }

        // GET: Discussion/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DiscussionVM discussion = await db.DiscussionVMs.FindAsync(id);
            if (discussion == null)
            {
                return HttpNotFound();
            }
            return View(discussion);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Politify/Controllers/OrganisationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Politify.Code;
using Politify.Models;


namespace Politify.Controllers
{
    public class OrganisationController : Controller
    {
        private PolitifyDbContext db = new PolitifyDbContext();

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrganisationVM org = await db.OrganisationVMs.FindAsync(id);
            if (org == null)
            {
                return HttpNotFound();
            }
            return View(org);
        }

        protected override void Dispose(bool disposing)
        {
            int num = disposing ? 1 : 0;
            base.Dispose(disposing);
        }
    }
}

Politify/Views/Shared/CountryDisplay.cshtml
@model Politify.Models.CountryViewModel

<img src="@Url.Content(Politify.Code.Constants.GetFlagFilePath(Model.ImageFileName, Politify.Code.Enums.FlagImageSize.Size48))" title="@Model.Name" />

Politify/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - EnVocal</title>
    @{
        string safeAppPath = Request.ApplicationPath == "/"? "": Request.ApplicationPath;
    }
    <link rel="shortcut icon" href="@(safeAppPath)/favicon.ico">
    <link rel="icon" sizes="16x16 32x32 64x64" href="@(safeAppPath)/Content/Favicons/favicon.ico">
    <link rel="icon" type="image/png" sizes="196x196" href="@(safeAppPath)/Content/Favicons/favicon-196.png">
    <link rel="icon" type="image/png" sizes="160x160" href="@(safeAppPath)/Content/Favicons/favicon-160.png">
    <link rel="icon" type="image/png" sizes="96x96" href="@(safeAppPath)/Content/Favicons/favicon-96.png">
    <link rel="icon" type="image/png" sizes="64x64" href="@(safeAppPath)/Content/Favicons/favicon-64.png">
    <link rel="icon" type="image/png" sizes="32x32" href="@(safeAppPath)/Content/Favicons/favicon-32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="@(safeAppPath)/Content/Favicons/favicon-16.png">
    <link rel="apple-touch-icon" sizes="152x152" href="@(safeAppPath)/Content/Favicons/favicon-152.png">
    <link rel="apple-touch-icon" sizes="144x144" href="@(safeAppPath)/Content/Favicons/favicon-144.png">
    <link rel="apple-touch-icon" sizes="120x120" href="@(safeAppPath)/Content/Favicons/favicon-120.png">
    <link rel="apple-touch-icon" sizes="114x114" href="@(safeAppPath)/Content/Favicons/favicon-114.png">
    <link rel="apple-touch-icon" sizes="76x76" href="@(safeAppPath)/Content/Favicons/favicon-76.png">
    <link rel="apple-touch-icon" sizes="72x72" href="@(safeAppPath)/Content/Favicons/favicon-72.png">
    <link rel="apple-touch-icon" href="@(safeAppPath)/Content/Favicons/favicon-57.png">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="@(safeAppPath)/Content/Favicons/favicon-144.png">
    <meta name="msapplication-config" content="/browserconfig.xml">
    <script type="text/javascript">
        var appPath = '@Request.ApplicationPath';
        var virtualPath = appPath + (appPath.substr(appPath.length - 1) == '/' ? '' : '/');
        var envocal = {
            functions: {},
            consts: {}
        };
    </script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/script")
    @Scripts.Render("~/bundles/viewModels")
    <link href="@Styles.Url("~/Content/site-mobile.css")" rel="stylesheet" type="text/css" media="screen and (max-width: 900px)" />
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-59217863-1', 'auto');
        ga('send', 'pageview');

    </script>
    <script type="text/javascript">
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": true,
            "progressBar": false,
            "positionClass": "toast-top-left",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="loader-animation navbar-ajax-loader navbar-icon right visible-xs-block" style="display:none !important;">
                    <span class="glyphicon glyphicon-refresh spin"></span>
                </div>
                <img src="@Url.Content(Politify.Code.Constants.FlagFilePath32() + "United Kingdom(Great Britain).png")"
                     title="Viewing site as 'United Kingdom' user."
                     class="navbar-country visible-xs-block" />
                <a href="@Url.Content("~")" title="EnVocal, crowd sourced politics.">
                    <div class="left">
                        <img src="@Url.Content("~/Content/Images/politify_logo-white.png")" alt="EnVocal, crowd sourced politics." class="logo" />
                        <div class="title-container">
                            <div class="title" title="EnVocal, crowd sourced politics.">EnVocal</div>
                            <div class="beta">ALPHA</div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="margin-left:45px;">
                    <li>@Html.ActionLink("Organisations", "Index", "Organisation")</li>
                    <li>@Html.ActionLink("Discussions", "Index", "Discussion")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @*<div id="loaderAnimation" class="navbar-ajax-loader navbar-icon right visible-" style="display:none;">
                    <span class="glyphicon glyphicon-refresh spin"></span>
                </div>*@
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p> <a href="@Url.Content("~/Home/PrivacyPolicy")">Privacy Policy</a> &nbsp;&nbsp;&nbsp; &copy; @DateTime.Now.Year - EnVocal</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>